embed_images: off

# There is a bug preventing code from working correctly if compressed.
compress_assets: off

javascripts:
  common:

  logged_in_only:
    - public/javascripts/user_voice.js
  project_page:
    - public/javascripts/jquery.history_remote.js
    - public/javascripts/jquery.tabs.js
    - public/javascripts/jcarousellite.js
  service_page:
    - public/javascripts/jquery.history_remote.js
    - public/javascripts/jquery.tabs.js
    - public/javascripts/jcarousellite.js  
  profile_page:
    - public/javascripts/jquery.history_remote.js
    - public/javascripts/jquery.tabs.js
  ie_fixes:
    - public/javascripts/correct_png.js

stylesheets:
  common:
    - public/stylesheets/screen.css
    - public/stylesheets/console.css
  project_page:
    - public/stylesheets/jquery_tabs.css
    - public/stylesheets/uploadify.css
  service_page:
    - public/stylesheets/jquery_tabs.css
    - public/stylesheets/uploadify.css    
  profile_page:
    - public/stylesheets/jquery_tabs.css
